### ISSUE TITLE
Number of waypoints

### ISSUE THREAD

**Issue by skyritsis** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#1]
Hello,
I cannot seem to be able to prepare a mission with only one waypoint. I am trying to create a point and go type application with just one point as a destination.
Is this a bug, or am I missing something?
Thank you in advance,
SK

**Comment by dji-dev** [comment]
Hello, if you want to use DJIWaypointMission, you should add at least two DJIWaypoint to prepare the mission. It's not a bug actually. For your case, maybe you can just modify the second waypoint's altitude a little bit, so that the Mission can start preparing? Hope this help.

**Comment by skyritsis** [comment]
Hello again. Thank you for your reply. From your answer I deduce that there is another way to do what I described above, without using DJIWaypointMission. Could you please point me to a direction where I can achieve the aforementioned objective, regardless of using DJIWaypointMission?
SK

**Comment by dji-dev** [comment]
Hi! Could you describe your objective more detailed？So I can provide you more suggestions. Thanks!
