### ISSUE TITLE
Spark

### ISSUE THREAD

**Issue by lillogoal** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#11]
Isn't available for spark, right ?
How can i do similar things with "SPARK" ? 
THanks

**Comment by oliverou** [comment]
Hi @lillogoal , WaypointMission doesn't support Spark. You can check this API Doc: <http://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMission.html>

**Comment by lillogoal** [comment]
Ok. I read. How can I pass the coordinates to the drone of a position to reach? @oliverou

**Comment by oliverou** [comment]
Hi @lillogoal , currently, Spark doesn't support waypointMission, so you cannot pass coordinates to it to reach. Close the ticket now.

**Comment by ybabs** [comment]
@oliverou  HI, will the simulation work with a Spark at the very least?

**Comment by oliverou** [comment]
Hi @InterestingWalrus, nope, DJI SDK doesn't support Waypoint Mission for Spark at all, includes simulation.
