### ISSUE TITLE
Mission start error

### ISSUE THREAD

**Issue by Asendo316** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#20]
Error when trying to start a mission.
Mission Start: The Mission start could not be executed.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33448'>Zendesk ticket #33448</a>:<br><br>Dear Client
Thank you for contacting DJI.

Make sure you upload the mission first.
Reference: https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=uploadmission&i=0&#djiwaypointmissionoperator_uploadmission_inline

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
