### ISSUE TITLE
Is this supposed to work with phantom 3?

### ISSUE THREAD

**Issue by augre** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#3]
Hi,

I am trying to get this work with phantom 3 standard or phantom 3 4k but would not connect to the aircraft. Is it supposed to work with those models?

Thanks!

**Comment by dji-dev** [comment]
Hi, currently the GSDemo doesn't support Phantom 3 Standard or Phantom 3 4K, we will consider to support them soon. Currently, please use Phantom 3 Professional, Inspire 1, or other USB connection products to test the GSDemo.

**Comment by augre** [comment]
Thank you for your response. Could I make this work with the phantom 3? I guess I need to change the USB communication part to airlink?

**Comment by dji-dev** [comment]
Hi, after the testing on iOS GSDemo, the GSDemo should support Phantom 3 Standard and Phantom 3 4K without changing any settings. We will investigate this problem in the Android SDK. Get back to you soon.

BTW, no need to change to airlink, it's not related to this problem.

**Comment by dji-dev** [comment]
Hi, after fully testing, we can run the Android GSDemo with Phantom 3 Standard successfully, please follow the tips below to run the demo:
1. Build and run the GSDemo on your android device (We use Nexus 5, Android 6.0 Marshmallow here)
2. Connect your drone to PC and use the PC Simulator to simulate the coordinate to the location you want as the tutorial said
3. Connect your android device to internet first to load the google map and then reconnect to the Phantom 3 Standard RC's network
4. Follow the tutorial to test the Waypoint features.

If you still cannot run the Android GSDemo successfully with Phantom 3 Standard, please provide the following details to us for investigating:
1. Which Android Device and Android System you are using?
2. Which version of Android Studio you are using?
3. Can you describe the situation on your side if it doesn't work on Phantom 3 Standard? Like the aircraft doesn't show in the map, etc.

Thanks!

**Comment by augre** [comment]
Thank you very much for the instructions! I am still testing, will leave a feedback soon.

**Comment by vascoV** [comment]
Hello,

I have some issues with my tablet that I am using for developing app for dji drone!
When I am connecting the tablet to the controler via usb I an supposed to olug and unplug the tablet to the controller many times and also it desn't wok when developer mode is enabled!! I am using Phantom 3 Advanced and Samsun Galaxy Tab S2 9.7" SM-T819

**Comment by dji-dev** [comment]
Will close this issue since original question is answerd.
@vascoV , Please feel free to open a separate issue for this.
