### ISSUE TITLE
Often app crashes when preparing the mission

### ISSUE THREAD

**Issue by IncognitoBA** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#5]
Using Lenovo TAB 2 A7-30HC (Android 4.4.2) app often crashes when I try to prepare the mission. But it works well when using Sony Xperia M2 Aqua (Android 5.1.1).  What is the reason?

**Comment by dji-dev** [comment]
Will go ahead and close this ticket as current version sdk (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
