### ISSUE TITLE
Custom coordinates on follow me mission

### ISSUE THREAD

**Issue by vascoV** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#7]
Is there a way to use custom coordinates in follow me mission?
smth like DJI: 
Double Lat: 33.22345;
Double Lon: 32.5678;

DjiFollowMe(Lat, Lon){
      executing the follow me mission
}

**Comment by dji-dev** [comment]
Please use:
`FollowMeMissionOperator.startMission(FollowMeMission ...);`
Pass in `FollowMeMission` as follow:
`FollowMeMission.getInstance().initUserData(lat,long,altitude)`

Thank you.
