### ISSUE TITLE
Problem at starting waypoint mission (related to location)

### ISSUE THREAD

**Issue by AeroOmar** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#9]
Hi I'm new and i don't know how works this tool, sorry if i do some mistake.

I am using the macro of waypoints provided by DJI based on google maps and is supposed that when your mission is ready and uploaded successfully (i reached that point) , as soon as you press start the dron should start flying toward the waypoints with any problem.

But i tried today to do this and i got a problem like "my location was not correct, or what the dron was not able to set its home location".

I am sorry but i can't give you the specific message of the error because the dron is not mine and i can't reproduce again the error maybe until some days later (Moreover i tried to find out the error on the toast messages on the source code but i couldn't).

Is this problem due to some poor receival of GPS signal or it deppends on other issues?

I'm using a DJI  phantom 4, android studio 2.2,  DJI SDK 4.0.2.  ,android version 5.1.1, and device Energy pro 4G.

Thank you beforehand!

**Comment by oliverou** [comment]
Hi @AeroOmar, thanks for the feedbacks. Please check the followings:
1. We have launched the Android SDK 4.1.1 recently, and the GSDemo has been updated to this latest version too. Could you download and try it again? 
2. Do you use the DJI Assistant 2 Simulator to test the GSDemo or go outside to test it?  You can follow the tutorial: [Creating a MapView and Waypoint Application](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/GSDemo-Google-Map.html#locating-aircraft-on-google-map) to learn how to use the Simulator to test it.
3. If you test the GSDemo outside, please make sure the GPS signal is strong, you can connect to DJI Go app first and make sure the aircraft has no issues (Check the checklist items). Then use the GSDemo to test again.

Hope these help!

**Comment by AeroOmar** [comment]
I tested it outside because I just have this dron few hours a week and was the faster method but i'll try the simulator. Firstly I'm  going to check the signal in the official app (I didn't think about that) and if all goes wrong I'll update the app yo the latest version, thank you so much  i close the thread :D
